#!/bin/sh

git subtree split --prefix=$1 --branch=$1
git push https://github.com/kungfudev/$1.git $1:master
git remote add $1 https://github.com/kungfudev/$1.git
git rm -r $1
git add -A
git commit -am "Splitting $1 into seperate repo"
